[gravity]
domain = "gravity"
host = "0.0.0.0:4222"

[subscriber]
subscriberID = "mssql_transmitter"
subscriberName = "MSSQL Transmitter"
stateStore = "./statestore"
workerCount = 4
chunkSize = 2048
verbose = true
pipelineStart = 0
pipelineEnd = -1

# Authentication
appID = "anonymous"
accessKey = ""

[initialLoad]
enabled = true
omittedCount = 100000

[bufferInput]
chunkSize = 100
#SQL Server supports a maximum of 2100 parameters. (chunkSize * columns must less than 2100)
timeout = 50
#unit: millisecond

[rules]
subscription = "./settings/subscriptions.json"

[database]
host = "0.0.0.0"
port = 1433
secure = false
username = "SA"
password = "1qaz@WSX"
dbname = "TestDB"
