[gravity]
domain = "gravity"
host = "0.0.0.0:4222"

[subscriber]
subscriber_id = "mssql_transmitter"
subscriber_name = "MSSQL Transmitter"
state_store = "./statestore"
worker_count = 4
verbose = true
pipeline_start = 0
pipeline_end = -1

[initial_load]
enabled = true
omitted_count = 100000


[rules]
subscription = "./settings/subscriptions.json"

[database]
host = "0.0.0.0"
port = 1433
secure = false
username = "SA"
password = "1qaz@WSX"
dbname = "TestDB"
