[gravity]
domain = "gravity"
host = "0.0.0.0:4222"

[subscriber]
subscriberID = "mssql_transmitter"
subscriberName = "MSSQL Transmitter"
stateStore = "./statestore"
workerCount = 4
verbose = true
pipelineStart = 0
pipelineEnd = -1

# Authentication
appID = "anonymous"
accessKey = ""

[initialLoad]
enabled = true
omittedCount = 100000


[rules]
subscription = "./settings/subscriptions.json"

[database]
host = "0.0.0.0"
port = 1433
secure = false
username = "SA"
password = "1qaz@WSX"
dbname = "TestDB"
